[package]
name = "nibarchive_downgrade"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nibarchive = {version = "*", path = "../nibarchive"}
plist = "1.6"
